language: objective-c
osx_image: xcode7.1

before_install:
  - brew update
  - brew install carthage
  - carthage bootstrap --verbose

xcode_project: TranslateKit.xcodeproj
xcode_scheme: TranslateKit

